# Cloud Build configuration for Shopping Optimizer
# This file defines the CI/CD pipeline for deploying to Google Cloud Run
#
# Trigger this build:
#   gcloud builds submit --config cloudbuild.yaml
#
# Or set up automatic triggers in Cloud Build console:
#   - Push to main branch -> deploy to production
#   - Push to staging branch -> deploy to staging
#   - Pull requests -> run tests only
#
# Requirements: 9.5

steps:
  # Step 1: Build the Docker image
  # Uses Cloud Build's Docker builder with caching for faster builds
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '--tag=gcr.io/$PROJECT_ID/shopping-optimizer:$COMMIT_SHA'
      - '--tag=gcr.io/$PROJECT_ID/shopping-optimizer:latest'
      - '--cache-from=gcr.io/$PROJECT_ID/shopping-optimizer:latest'
      - '--build-arg=BUILDKIT_INLINE_CACHE=1'
      - '.'
    timeout: 600s

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/shopping-optimizer:$COMMIT_SHA'
    waitFor: ['build-image']

  # Step 3: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/shopping-optimizer:latest'
    waitFor: ['build-image']

  # Step 4: Deploy to Cloud Run
  # This step deploys the container to Cloud Run with all necessary configuration
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'shopping-optimizer'
      - '--image=gcr.io/$PROJECT_ID/shopping-optimizer:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      # Resource allocation
      - '--memory=${_MEMORY}'
      - '--cpu=${_CPU}'
      - '--timeout=${_TIMEOUT}'
      - '--max-instances=${_MAX_INSTANCES}'
      - '--min-instances=${_MIN_INSTANCES}'
      # Concurrency and scaling
      - '--concurrency=${_CONCURRENCY}'
      # VPC connector for Redis (Memorystore)
      - '--vpc-connector=${_VPC_CONNECTOR}'
      - '--vpc-egress=${_VPC_EGRESS}'
      # Environment variables (non-sensitive)
      - '--set-env-vars=ENVIRONMENT=${_ENVIRONMENT}'
      - '--set-env-vars=LOG_LEVEL=${_LOG_LEVEL}'
      - '--set-env-vars=AGENT_MODEL=${_AGENT_MODEL}'
      - '--set-env-vars=AGENT_TEMPERATURE=${_AGENT_TEMPERATURE}'
      - '--set-env-vars=CACHE_TYPE=redis'
      - '--set-env-vars=CACHE_TTL_SECONDS=${_CACHE_TTL_SECONDS}'
      - '--set-env-vars=ENABLE_AI_MEAL_SUGGESTIONS=true'
      - '--set-env-vars=ENABLE_CACHING=true'
      - '--set-env-vars=ENABLE_METRICS=true'
      - '--set-env-vars=ENABLE_STRUCTURED_LOGGING=true'
      # Secrets (sensitive data from Secret Manager)
      - '--set-secrets=GOOGLE_API_KEY=google-api-key:latest'
      - '--set-secrets=SALLING_GROUP_API_KEY=salling-api-key:latest'
      - '--set-secrets=REDIS_URL=redis-url:latest'
      # Service account for accessing other GCP services
      - '--service-account=${_SERVICE_ACCOUNT}'
      # Labels for organization
      - '--labels=app=shopping-optimizer,environment=${_ENVIRONMENT},managed-by=cloud-build'
    waitFor: ['push-image', 'push-latest']
    timeout: 600s

# Substitution variables with defaults
# Override these when triggering the build:
#   gcloud builds submit --config cloudbuild.yaml --substitutions=_ENVIRONMENT=production
substitutions:
  # Deployment configuration
  _REGION: 'us-central1'
  _ENVIRONMENT: 'production'
  
  # Resource allocation
  _MEMORY: '2Gi'
  _CPU: '2'
  _TIMEOUT: '300s'
  
  # Auto-scaling configuration
  _MAX_INSTANCES: '10'
  _MIN_INSTANCES: '1'
  _CONCURRENCY: '80'
  
  # VPC configuration for Redis
  _VPC_CONNECTOR: 'shopping-optimizer-vpc'
  _VPC_EGRESS: 'private-ranges-only'
  
  # Application configuration
  _LOG_LEVEL: 'INFO'
  _AGENT_MODEL: 'gemini-2.0-flash-exp'
  _AGENT_TEMPERATURE: '0.7'
  _CACHE_TTL_SECONDS: '3600'
  
  # Service account
  _SERVICE_ACCOUNT: 'shopping-optimizer@${PROJECT_ID}.iam.gserviceaccount.com'

# Build options
options:
  # Use high-performance machine type for faster builds
  machineType: 'N1_HIGHCPU_8'
  
  # Logging configuration
  logging: CLOUD_LOGGING_ONLY
  
  # Timeout for entire build
  timeout: 1200s
  
  # Substitute variables in all steps
  substitution_option: 'ALLOW_LOOSE'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/shopping-optimizer:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/shopping-optimizer:latest'

# Build timeout
timeout: 1200s
